// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// read_data
RcppExport SEXP read_data(Rcpp::String stringname);
RcppExport SEXP _VCM_read_data(SEXP stringnameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type stringname(stringnameSEXP);
    rcpp_result_gen = Rcpp::wrap(read_data(stringname));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VCM_read_data", (DL_FUNC) &_VCM_read_data, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_VCM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
